#remote_theme: pages-themes/modernist@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#show_downloads: false
google_analytics: G-ET8J5M70MY
plugins:
  - jekyll-remote-theme
remote_theme: zivhub/monophase@main
